// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceihspktqaflxpyjoeds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlaWhzcGt0cWFmbHhweWpvZWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTIzMDcsImV4cCI6MjA2NTY2ODMwN30.6RuaIBNGEa5m09t3p6R3Ffc0DdYv5NjXPJKOgkO6piA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);